//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printer_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Printer_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Installed.
        /// </summary>
        internal static string ApplicationInstalledPrompt {
            get {
                return ResourceManager.GetString("ApplicationInstalledPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Uninstalled.
        /// </summary>
        internal static string ApplicationUninstalledPrompt {
            get {
                return ResourceManager.GetString("ApplicationUninstalledPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find configuration file in the current directory.
        ///Or the configuration file is corrupted..
        /// </summary>
        internal static string ConfigurationFileNotFoundPrompt {
            get {
                return ResourceManager.GetString("ConfigurationFileNotFoundPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save your user name and password to the configuration file.
        ///Or the configuration file is corrupted..
        /// </summary>
        internal static string CredentialFailedSavdPrompt {
            get {
                return ResourceManager.GetString("CredentialFailedSavdPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username does not match your password.
        ///Please re-check your username and password or the Internet connection..
        /// </summary>
        internal static string CredentialIncorrectPrompt {
            get {
                return ResourceManager.GetString("CredentialIncorrectPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username and password is stored securely!.
        /// </summary>
        internal static string CredentialSuccessfulSavdPrompt {
            get {
                return ResourceManager.GetString("CredentialSuccessfulSavdPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait before when checking your username and password..
        /// </summary>
        internal static string CredentialWaitForCheckingCompletePrompt {
            get {
                return ResourceManager.GetString("CredentialWaitForCheckingCompletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run this app with administrator permission..
        /// </summary>
        internal static string NonAdminPrompt {
            get {
                return ResourceManager.GetString("NonAdminPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Problem was encoutered while saving.
        ///Please make sure the configuration file is readable and writable.
        /// </summary>
        internal static string OptionFailedSavedPrompt {
            get {
                return ResourceManager.GetString("OptionFailedSavedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options saved successufully!.
        /// </summary>
        internal static string OptionSuccessfulSavedPrompt {
            get {
                return ResourceManager.GetString("OptionSuccessfulSavedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Printer {
            get {
                object obj = ResourceManager.GetObject("Printer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successful!
        ///Right on any file to print..
        /// </summary>
        internal static string SavePrinterSuccessfulPrompt {
            get {
                return ResourceManager.GetString("SavePrinterSuccessfulPrompt", resourceCulture);
            }
        }
    }
}
